**Python Module for Data Science - Numpy**

In [ ]:
x = 9
print(x * 2)

18


In [ ]:
a = [6,5,4,8,3]
print(a)
print(a * 2)

[6, 5, 4, 8, 3]
[6, 5, 4, 8, 3, 6, 5, 4, 8, 3]


In [ ]:
for i in range(0,len(a)):
  a[i] = a[i] * 2
print(a)

[12, 10, 8, 16, 6]


In [ ]:
import numpy as np

n1 = np.array([6,5,4,8,3])
print(n1)

[6 5 4 8 3]


In [ ]:
print(n1 * 2)

[12 10  8 16  6]


In [ ]:
n2 = np.array([[1,2,3,4,5] , [4,8,3,2,1] , [9,8,7,6,5]])
print(n2)

[[1 2 3 4 5]
 [4 8 3 2 1]
 [9 8 7 6 5]]


In [ ]:
print(n2.shape)
print(n2.ndim)
print(n2.size)

(3, 5)
2
15


In [ ]:
print(n2)

[[1 2 3 4 5]
 [4 8 3 2 1]
 [9 8 7 6 5]]


In [ ]:
#functions of Numpy
print(np.sum(n2))
print(np.min(n2))
print(np.max(n2))
print(np.mean(n2))
print(np.std(n2))
print(np.var(n2))
print(np.median(n2))
print(np.argmax(n2))
print(np.argmin(n2))

68
1
9
4.533333333333333
2.5263060428661888
6.3822222222222225
4.0
10
0


In [ ]:
print(n2)

[[1 2 3 4 5]
 [4 8 3 2 1]
 [9 8 7 6 5]]


In [ ]:
#functions of Numpy -> valculation made on each row
print(np.sum(n2 , axis = 1))
print(np.min(n2 , axis = 1))
print(np.max(n2 , axis = 1))
print(np.mean(n2 , axis = 1))
print(np.std(n2 , axis = 1))
print(np.var(n2 , axis = 1))
print(np.median(n2 , axis = 1))
print(np.argmax(n2 , axis = 1))
print(np.argmin(n2 , axis = 1))

[15 18 35]
[1 1 5]
[5 8 9]
[3.  3.6 7. ]
[1.41421356 2.41660919 1.41421356]
[2.   5.84 2.  ]
[3. 3. 7.]
[4 1 0]
[0 4 4]


In [ ]:
#functions of Numpy -> valculation made on each columns
print(np.sum(n2 , axis = 0))
print(np.min(n2 , axis = 0))
print(np.max(n2 , axis = 0))
print(np.mean(n2 , axis = 0))
print(np.std(n2 , axis = 0))
print(np.var(n2 , axis = 0))
print(np.median(n2 , axis = 0))
print(np.argmax(n2 , axis = 0))
print(np.argmin(n2 , axis = 0))

[14 18 13 12 11]
[1 2 3 2 1]
[9 8 7 6 5]
[4.66666667 6.         4.33333333 4.         3.66666667]
[3.29983165 2.82842712 1.88561808 1.63299316 1.88561808]
[10.88888889  8.          3.55555556  2.66666667  3.55555556]
[4. 8. 3. 4. 5.]
[2 1 2 2 0]
[0 0 0 1 1]


In [ ]:
#Selecting a row or a column => slicing

print(n2)

[[1 2 3 4 5]
 [4 8 3 2 1]
 [9 8 7 6 5]]


In [ ]:
print(n2[0,1])       #array[row_index , column_index]
print(n2[1,0])
print(n2[1,3])

2
4
2


In [ ]:
print("Row zero" , n2[0])
print()
print("Row One" , n2[1])
print()
print("Row two" , n2[2])

Row zero [1 2 3 4 5]

Row One [4 8 3 2 1]

Row two [9 8 7 6 5]


* array[row slicing , column slicing]
* array[row_initial_index : row_initial_index + number of rows , col_initial_index : col_initial_index + number of columns]

In [ ]:
n2[:,0:1]

array([[1],
       [4],
       [9]])

In [ ]:
n2[:,1:2]

array([[2],
       [8],
       [8]])

In [ ]:
n2[:,2:4]

array([[3, 4],
       [3, 2],
       [7, 6]])

In [ ]:
print(n2)

[[1 2 3 4 5]
 [4 8 3 2 1]
 [9 8 7 6 5]]


In [ ]:
print(n2[1:3,1:4])

[[8 3 2]
 [8 7 6]]


In [ ]:
print(n2[:,3:4])

[[4]
 [2]
 [6]]


In [ ]:
n3 = np.arange(0,36)        #array + range
print(n3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
#36 => (6,6),(4,9),(9,4),(3,12),(12,3),(2,18),(18,2),(1,36),(36,1)
n4 = n3.reshape(6,6)
print(n4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
print(n4[2:6 , 3:6])

[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]


In [ ]:
print(n4[:,5:6])

[[ 5]
 [11]
 [17]
 [23]
 [29]
 [35]]


In [ ]:
print(np.zeros([4,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones([4,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Broadcasting**

In [ ]:
a = np.array([[3,2,1,5] , [1,2,4,3]])
print(a)

[[3 2 1 5]
 [1 2 4 3]]


In [ ]:
b = 2

In [ ]:
print(a*b)

[[ 6  4  2 10]
 [ 2  4  8  6]]


In [ ]:
c = [1,2,3,4]
print(a * c)

[[ 3  4  3 20]
 [ 1  4 12 12]]


In [ ]:
print(a)

[[3 2 1 5]
 [1 2 4 3]]


In [ ]:
d = [[1],[2]]

print(a * d)

[[3 2 1 5]
 [2 4 8 6]]


In [ ]:
print(a)

[[3 2 1 5]
 [1 2 4 3]]


In [ ]:
e = np.array([[1,2],[3,4]])
print(e)

[[1 2]
 [3 4]]


In [ ]:
print(a*e)

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [ ]:
f = np.array([[1],[3]])
print(f)

[[1]
 [3]]


In [ ]:
print(a*f)

[[ 3  2  1  5]
 [ 3  6 12  9]]


* array()
* mathematical_functions - sum(),mean(),min(),max() etc.
* slicing
* arange()
* reshape()
* zeros()
* ones()
* eye()
* broadcasting